apiVersion: apps/v1
kind: Deployment
metadata:
  name:  laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      initContainers:
        - name: laravel-init
          image: zhddoc/laravelapp:v1
          command:
            - sh
            - -c
            - |
              php artisan config:cache && \
              php artisan migrate --force
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          # volumeMounts:
          #   - name: app-volume
          #     mountPath: /var/www/html
      containers:
      - name: laravel-app
        image: zhddoc/laravelapp:v1
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secret
        # volumeMounts:
        #     - name: app-volume
        #       mountPath: /var/www/html
      # volumes:
      #   - name: app-volume
      #     emptyDir: {}
--- 
apiVersion: v1 
kind: Service
metadata:
  name: laravel-app-service
spec:
  type: ClusterIP
  selector:
    app: laravel-app
  ports:
  - port: 80
    targetPort: 80
  